<x-layouts.app title="Panel de Control" eyebrow="Principal">
    <div class="space-y-6">
        <section class="relative overflow-hidden rounded-2xl border border-slate-200/80 bg-white p-6 shadow-sm dark:border-slate-800/90 dark:bg-slate-900 sm:p-8">
            <div class="absolute -right-12 -top-16 h-64 w-64 rounded-full bg-emerald-50 blur-3xl dark:bg-emerald-950/40"></div>
            <div class="relative max-w-3xl">
                <x-badge>✓ Sistema Integrado de Gestión Institucional</x-badge>
                <h2 class="mt-4 text-2xl font-bold tracking-tight dark:text-white sm:text-3xl">Panel de Control Administrativo</h2>
                <p class="mt-2 max-w-2xl text-sm leading-relaxed text-slate-600 dark:text-slate-300">Bienvenido al portal corporativo. Monitorea presupuestos, tramitaciones departamentales y auditorías conforme a normativas vigentes.</p>
                <div class="mt-5 flex flex-wrap gap-3"><x-button href="{{ route('blank') }}">＋ Nuevo Trámite</x-button><x-button href="{{ route('blank') }}" variant="secondary">⇩ Exportar Reporte</x-button></div>
            </div>
        </section>
        <section class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            @foreach([['Presupuesto Ejecutado', '$91,400.00', '+12.5%', '↗', 'emerald'], ['Trámites Atendidos', '675', '+8.4%', '▣', 'sky'], ['Tiempo de Respuesta', '2.4 días', '-18.2%', '◷', 'amber'], ['Cumplimiento Normativo', '98.6%', '+2.1%', '✓', 'violet']] as [$label, $value, $change, $icon, $color])
                <x-card class="p-5"><div class="mb-3 flex items-center justify-between"><p class="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">{{ $label }}</p><span class="rounded-xl bg-{{ $color }}-50 p-2 text-{{ $color }}-600 dark:bg-{{ $color }}-950/50">{{ $icon }}</span></div><p class="text-2xl font-bold tracking-tight dark:text-white">{{ $value }}</p><p class="mt-2 text-xs font-semibold text-emerald-600">{{ $change }} vs periodo anterior</p></x-card>
            @endforeach
        </section>
        <section class="grid gap-6 xl:grid-cols-5">
            <x-card class="xl:col-span-3"><div class="flex items-center justify-between border-b border-slate-100 px-6 py-5 dark:border-slate-800"><div><h3 class="font-bold dark:text-white">Ejecución presupuestaria</h3><p class="mt-1 text-xs text-slate-500 dark:text-slate-400">Presupuesto vs ejecutado · 2026</p></div><x-badge variant="info">Mensual</x-badge></div><div class="flex h-64 items-end gap-2 px-6 pb-6 pt-8 sm:gap-4">@foreach([45,52,58,64,70,75,82,88,94] as $height)<div class="group flex flex-1 flex-col items-center gap-2"><div class="w-full rounded-t-lg bg-emerald-500 transition group-hover:bg-emerald-600" style="height: {{ $height * 2.1 }}px"></div><span class="text-[10px] text-slate-400">{{ ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep'][$loop->index] }}</span></div>@endforeach</div></x-card>
            <x-card class="xl:col-span-2"><div class="border-b border-slate-100 px-6 py-5 dark:border-slate-800"><h3 class="font-bold dark:text-white">Estado de trámites</h3><p class="mt-1 text-xs text-slate-500 dark:text-slate-400">Distribución del periodo actual</p></div><div class="space-y-4 p-6">@foreach([['Aprobados',58,'emerald'],['En Revisión',24,'sky'],['Pendientes',12,'amber'],['Rechazados',6,'red']] as [$label,$percent,$color])<div><div class="mb-1.5 flex justify-between text-xs font-semibold dark:text-slate-200"><span>{{ $label }}</span><span class="text-slate-500 dark:text-slate-400">{{ $percent }}%</span></div><div class="h-2 rounded-full bg-slate-100 dark:bg-slate-800"><div class="h-2 rounded-full bg-{{ $color }}-500" style="width: {{ $percent }}%"></div></div></div>@endforeach</div></x-card>
        </section>
        <x-card><div class="border-b border-slate-100 px-6 py-5 dark:border-slate-800"><h3 class="font-bold dark:text-white">Actividad reciente</h3><p class="mt-1 text-xs text-slate-500 dark:text-slate-400">Últimos expedientes registrados</p></div><div class="overflow-x-auto"><table class="w-full min-w-[700px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500 dark:bg-slate-800/70 dark:text-slate-400"><tr><th class="px-6 py-3">Expediente</th><th class="px-6 py-3">Trámite</th><th class="px-6 py-3">Departamento</th><th class="px-6 py-3">Estado</th><th class="px-6 py-3 text-right">Monto</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@foreach([['EXP-FIN-8841','Adquisición de Equipamiento Informático','Tecnología y Sistemas','Aprobado','$148,500'],['EXP-RRHH-4120','Convocatoria Pública de Personal','Recursos Humanos','En Revisión','$32,000'],['EXP-LEG-1092','Contrato Marco de Mantenimiento','Dirección Jurídica','Pendiente','$89,400'],['EXP-AUD-3301','Dictamen de Auditoría Trimestral','Contraloría Interna','Aprobado','$0']] as [$code,$name,$dept,$status,$amount])<tr class="hover:bg-slate-50 dark:hover:bg-slate-800/60"><td class="px-6 py-4 font-semibold text-emerald-700">{{ $code }}</td><td class="max-w-xs truncate px-6 py-4 font-medium dark:text-slate-200">{{ $name }}</td><td class="px-6 py-4 text-slate-500 dark:text-slate-400">{{ $dept }}</td><td class="px-6 py-4"><x-badge variant="{{ $status === 'Aprobado' ? 'success' : ($status === 'Pendiente' ? 'warning' : 'info') }}">{{ $status }}</x-badge></td><td class="px-6 py-4 text-right font-semibold dark:text-slate-200">{{ $amount }}</td></tr>@endforeach</tbody></table></div></x-card>
    </div>
</x-layouts.app>
